###
GET http://{{host}}:59097/s3/minio/buckets
###
GET http://{{host}}:59097/s3/amazon/buckets

###
GET http://{{host}}:59097/s3/minio/common

###
GET http://{{host}}:59097/s3/amazon/appelation

###
GET http://{{host}}:59097/s3/minio/appelation/Виновное лицо.docx

###
GET http://{{host}}:59097/s3/amazon/appelation/Виновное лицо.docx

###
DELETE http://{{host}}:59097/s3/minio/appelation/Виновное лицо.docx

###
DELETE http://{{host}}:59097/s3/amazon/appelation/Виновное лицо.docx

###

# curl --location --request POST 'http://localhost:59097/s3/minio/mystorage/folder2'--form 'file=@"/mnt/c/Users/Kotin/Downloads/atrack3-grafana.png"'
POST http://{{host}}:59097/s3/minio/common/folder5
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="atrack3-grafana.png"

< "/Users/Kotin/Downloads/atrack3-grafana.png"
--WebAppBoundary--

###
# curl --location --request POST 'http://localhost:59097/s3/minio/myfile/f2' --form 'file=@"/C:/Users/Kotin/Downloads/test form500.jpg"'
POST http://localhost:59097/s3/minio/myfile/f2
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test form500.jpg""

< "\C:\Users\Kotin\Downloads\test form500.jpg"
--WebAppBoundary--

###

###
GET http://localhost:59097/s3/show/minio/taganrog-mobile/14_МП Таганрог.jpg
Accept-Charset: UTF-8
###
GET http://localhost:59097/s3/minio/taganrog-mobile/11_14_06_2022.jpg
Content-Type: image/jpeg
